stages:
  - build

docker build and publish:
  stage: build
  only:
    - master
    - dev
  image:
    name: docker:19.03
  script:
    - docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PASSWORD
    - docker build --pull -t $CI_REGISTRY/$NAME_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY/$NAME_IMAGE:$CI_COMMIT_REF_NAME --no-cache --build-arg BRANCH_ARG=$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY/$NAME_IMAGE





