server:
  ssl:
    key-store-password: changeit
    key-store-type: PKCS12
    enabled: 'true'
    key-store: classpath:java_ssl.p12

spring:
  jpa:
    generate-ddl: 'true'
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          query:
            timeout: '0'
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: '5'
    username: postgres
    url: jdbc:postgresql://localhost:5432/SupBotAdmin
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'

telegram:
  url:
    webapp: https://192.168.110.84:3000/
    #=== product ===#
    nameBot: @sup31_bot
    tokenBot: 5617783598:AAEVI_edk9ptSp6aFrj
    #=== test ===#
#  nameBot: '@SupAdminTest_bot'
#  tokenBot: 5655610927:AAG58hHGVMC9OdMkS2lfRYa5DbzxgvXBOa4
