package com.bot.sup.common.enums;

public enum CallbackEnum {
    MENU,
    ABOUT_US_INFO,
    ADD_ABOUT_US_INFO,

    // РАСПИСАНИЕ
    SCHEDULE,
    SCHEDULE_TO_ACTIVITYFORMAT,
    DATE_TO_ROUTE,
    SCHEDULE_WEBAPP,
    ACTIVITYFORMAT_TO_DATE,
    SCHEDULE_INFO,
    SCHEDULE_DESCRIPTION,
    SCHEDULE_CANCEL,
    SCHEDULE_CANCEL_NO,
    SCHEDULE_CANCEL_YES,
    SCHEDULE_ALL_CLIENT_INFO,
    CLIENT_INFO,
    SCHEDULE_CLIENT_CANCEL,
    CLIENT_CANCEL_YES,
    CLIENT_CANCEL_NO,
    CLIENT_RECORD,
    // ИНСТРУКТОРЫ
    INSTRUCTORS,
    LIST_INSTRUCTORS,
    INSTRUCTOR_OPTION,
    DELETE_INSTRUCTOR,
    ADD_INSTRUCTOR,
    CHANGE_INSTRUCTOR,

    //АКТИВНОСТИ
    SUP_ACTIVITIES,
    SUP_ACTIVITY_FORMAT,
    SUP_ACTIVITY_TYPE,
    LIST_ACTIVITY_FORMAT,
    LIST_ACTIVITY_TYPE,
    ADD_ACTIVITY_FORMAT,
    ADD_ACTIVITY_TYPE,
    ACTIVITY_FORMAT_OPTION,
    ACTIVITY_TYPE_OPTION,
    ACTIVITY_FORMAT_CHANGE,
    ACTIVITY_TYPE_CHANGE,
    DELETE_ACTIVITY_FORMAT,
    DELETE_ACTIVITY_TYPE,
}
