package com.bot.sup.common.enums;

public enum CallbackEnum {
    MENU,

    // РАСПИСАНИЕ
    SCHEDULE,
    LIST_SCHEDULE,
    SCHEDULE_WEBAPP,
    SCHEDULE_ACTIVITY,
    SCHEDULE_OPTION,

    // ИНСТРУКТОРЫ
    INSTRUCTORS,
    LIST_INSTRUCTORS,
    INSTRUCTOR_OPTION,
    DELETE_INSTRUCTOR,
    ADD_INSTRUCTOR,
    CHANGE_INSTRUCTOR,

    //АКТИВНОСТИ
    SUP_ACTIVITIES,
    SUP_ACTIVITY_FORMAT,
    SUP_ACTIVITY_TYPE,
    LIST_ACTIVITY_FORMAT,
    LIST_ACTIVITY_TYPE,
    ADD_ACTIVITY_FORMAT,
    ADD_ACTIVITY_TYPE,
    ACTIVITY_FORMAT_OPTION,
    ACTIVITY_TYPE_OPTION,
    ACTIVITY_FORMAT_CHANGE,
    ACTIVITY_TYPE_CHANGE,
    DELETE_ACTIVITY_FORMAT,
    DELETE_ACTIVITY_TYPE,
}
